# Generated by Django 3.0.7 on 2020-06-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='SyncData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField()),
                ('created', models.DateTimeField()),
                ('dataString0', models.CharField(max_length=200)),
                ('dataString1', models.CharField(max_length=200)),
                ('dataString2', models.CharField(max_length=200)),
                ('dataString3', models.CharField(max_length=200)),
                ('dataString4', models.CharField(max_length=200)),
                ('dataString5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=1)),
                ('currentData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.SyncData')),
                ('syncBag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.SyncBag')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syncData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.SyncData')),
                ('syncItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.SyncItem')),
            ],
        ),
    ]
